config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  resources :apod, only: :index
  resources :bruce, only: :index
  resources :planets, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about_me.rb
class AboutMe < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compositor.rb
class Compositor
  attr_reader :seed
  attr_reader :planet

  def initialize(planet)
    @planet = planet
    @seed = hash(planet)
  end

  def self.glob(subdir, suffix)
    Dir.glob("#{Rails.root}/app/assets/images/#{subdir}/*#{suffix}").tap do |list|
      self.class_variable_set "@@#{subdir}_length".to_sym, list.length
    end
  end

  # BACKGROUNDS = glob('planets', '.jpg').freeze
  EYES = glob('eyes', '.png').freeze

  # def background_file
  #   BACKGROUNDS[seed % @@planets_length]
  # end

  def foreground_file
    EYES[seed % @@eyes_length]
  end

  def background
    @background ||= begin
      rotations = seed % 4
      # use `background_file` eventually but right now just pick the first because **COLOR**
      canvas = ChunkyPNG::Image.from_file("app/assets/images/planets/#{planet}/000.jpg")
      rotations.times {|_| canvas.rotate_right! }
      canvas
    end
  end

  def foreground
    retries = 0
    @foreground ||= begin
      image = ChunkyPNG::Image.from_file foreground_file
      width = (background.width * 0.4).round
      aspect_ratio = image.width / image.height
      height = (width / aspect_ratio).round
      image.resample_bilinear!(width, height)
      image
    rescue
      @seed += 1
      retries += 1
      retries < 5 ? retry : raise
    end
  end

  def composite
    @composite ||= background.compose(foreground, x_offset, y_offset)
  end

  def x_offset
    ((background.width - foreground.width) / 2) + offset_noise
  end

  def y_offset
      (background.height - foreground.height) / 4
  end

  def hash(str)
    Digest::MD5.hexdigest(str).to_i(16)
  end

  def offset_noise
    pos_neg = [1,-1].sample
    ((seed % 120) - 60) * pos_neg
  end
end

app/models/planet.rb
class Planet < ApplicationRecord
  alias_attribute :name, :pl_name
  alias_attribute :controversial, :pl_controvflag
end

app/controllers/apod_controller.rb
class ApodController < ApplicationController
  API_KEY = 'OoiyIsfU02IFuP9QBSZD38VBEy6BSHDyHUYDtfm2'
  def index
    response = HTTP.get('https://api.tronalddump.io/random/quote')
    quote_resp = JSON.parse(response.body)
    date = Time.parse(quote_resp["appeared_at"]).to_date
    @text= quote_resp["value"]
    puts date
    @nasa_resp = HTTP.get("https://api.nasa.gov/planetary/apod?date=#{date}&api_key=#{API_KEY}")
    @url = JSON.parse(@nasa_resp.body)["url"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bruce_controller.rb
class BruceController < ApplicationController
  def index
    @all_items = JSON.parse(HTTP.get('https://ssd-api.jpl.nasa.gov/sentry.api?ip-min=1e-4').body)['data']
    @selected = params[:des].present? ? @all_items.find { |i| i['des'] == params[:des] } : @all_items.sample
    @selected_des = @selected['des']
    @item_req = JSON.parse(HTTP.get("https://ssd-api.jpl.nasa.gov/sentry.api?des=#{@selected_des}").body)['summary']
    max_prob = [@item_req['ps_cum'].to_f, @item_req['ps_max'].to_f].max
    @cat = category_for(max_prob)
  end

  def category_for(max_prob)
    case max_prob
    when -Float::INFINITY..-5.5
      'low'
    when -5.5..-5.0
      'med'
    when -5.0..-4.5
      'medhigh'
    when -4.5..-4.0
      'high'
    else
      'death'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:name]
      @planet = Planet.find_by(pl_name: params[:name])
    else
      @planet = Planet.order('RANDOM()').first
    end
    # @images = Dir["app/assets/images/planets/#{@planet.pl_name}/*.jpg"]
    @composition = Compositor.new(@planet.name).composite
    render is_match? ? 'match' : 'index'
  end

  private

  def random_string
    (0...8).map { (65 + rand(26)).chr }.join
  end

  def is_match?
    params[:like] && rand(10) < 5
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:loc_rowid, :pl_hostname, :pl_letter, :pl_name, :pl_controvflag, :pl_pnum, :pl_orbper, :pl_orbsmax, :pl_orbeccen, :pl_orbincl, :pl_bmassj, :pl_radj, :pl_dens, :pl_nnotes, :st_dist, :gaia_dist, :st_optmag, :st_optband, :gaia_gmag, :st_teff, :st_mass, :st_rad, :rowupdate, :pl_eqt, :pl_masse, :pl_ratdor, :pl_ratror, :pl_status, :pl_mnum, :pl_publ_date)
    end
end

app/helpers/apod_helper.rb
module ApodHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bruce_helper.rb
module BruceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/apod/index.html.erb
<div class="apod">
  <%= image_tag @url %>
  <p><%= @text %></p>
</div>

app/views/bruce/index.html.erb
<script type="text/javascript">
function changeSelection(e) {
  window.location = window.location.href.split('?')[0] + '?des=' + e.value;
}
</script>
<div class="bruce">
  <h1>Is Bruce Willis Going To Have to Die?</h1>
  <select onchange="changeSelection(this)">
    <% @all_items.each do |item| %>
      <option value="<%= item['des'] %>" <%= 'selected' if item['des'] == @selected['des'] %>><%= item['des'] %></option>
    <% end %>
  </select>

  <p>For the body designated <b><%= @item_req['des'] %></b> things look <%= ['low', 'medhigh'].include?(@cat) ? 'good' : 'not so good' %>.
  See, it weighs <%= number_with_precision(("%f" %  @item_req['mass']).to_i * 0.00110231, delimiter: ',', precision: 0) %> tons, and it would hit at <%= number_with_precision(("%f" % @item_req['v_imp']).to_f * 2.23694, delimiter: ',', precision: 1) %> mph.
  </p>
  <% if @item_req['date'] %>
    Best guess, Bruce Willis has until <%= Date.parse(@item_req['date']) %> before he has to sacrifice himself
  <% end %>

  <ul class="classes">
    <% %w(low med medhigh high death).each_with_index do |level, i| %>
      <li class="<%= 'selected' if @cat == level %>">
        <%= image_tag "#{level}.jpg"%>
        <%= ["Should be fine", "Sorta risky, but feeling good", "Oh bring it on", "HARRRYYYYYY", "He's basically already dead."][i] %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/index.html.erb
<h1>XOPlanet</h1>
<script type="text/javascript">
  function handleClick(match, name) {
    if(match) {
      window.location = `/?like=${name}`;
    } else {
      window.location = "/";
    }
  }
</script>
<div class="wrapper">
  <div class="container">
    <nav>
      <span>Back</span>
      <%= image_tag('Logo.svg', class: 'logo') %>
    </nav>
    <main>
      <img class="photo" src="<%= @composition.to_data_url %>" width="375"/>
    </main>
    <div class="text">
      <h2><%= @planet.pl_name %></h2>
      <p><%= @planet.st_dist %> parsecs away</p>
      <br />
      <h3>ABOUT ME</h3>
      <p><%= AboutMe.order('RANDOM()').first.description.truncate(140) %></p>
      <br />
      <h3>MASS</h3>
      <p><%= @planet.st_mass %></p>
      <h3>EFFECTIVE TEMPERATURE</h3>
      <p><%= @planet.st_teff %></p>
      <h3>ORBIT SEMI-MAJOR AXIS</h3>
      <p><%= @planet.pl_orbsmax %></p>
    </div>
<!--
     <img src="<%= @composition.to_data_url %>" width="375"/>
      <a href="/" >
        <%= image_tag('dislike.svg', id: "dislike-button") %>
      </a>
      <a href="/?like=<%= @name %>" id="like-button" >
        <%= image_tag('like.svg') %>
      </a> %>
      -->
    </main>
    <div class="responses">
      <div class="no" >
        <a onclick="handleClick(false, '<%= @name %>')">
          <%= image_tag('dislike.svg', id: "dislike-button") %>
        </a>
      </div>
      <div class="yes">
        <a onclick="handleClick(true, '<%= @name %>')">
          <%= image_tag('like.svg', id: "like-button") %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/home/match.html.erb
<h1>XOPlanet</h1>
<p>Name: <%= @name %></p>
<script type="text/javascript">
  function handleClick(match, name) {
    if(match) {
      window.location = `/?like=${name}`;
    } else {
      window.location = "/";
    }
  }
</script>
<div class="wrapper">
  <div class="container">
    <nav>
      <%= image_tag('Logo.svg', class: 'logo') %>
    </nav>
    <section>
      <h2>It's a match!</h2>
      <div class="redcircle"></div>
      <div class="greencircle">
        <%= image_tag('like.svg', size: '120x120') %>
      </div>
      <div class="me">
        <%= image_tag('earth-3.png') %>
      </div>
      <div class="them">
        <img class="photo" src="<%= @composition.to_data_url %>" width="120"/>
      </div>
      <div class="purplecircle"></div>
      <p class="message">You’ll die before you get there… but the journey is more important than the destination, right?</p>
      <a class="button primary" href="/">Send a Message</a>
      <a class="button" href="/">Keep Looking</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XOplanet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>

<table>
  <thead>
    <tr>
      <th>Loc rowid</th>
      <th>Pl hostname</th>
      <th>Pl letter</th>
      <th>Pl name</th>
      <th>Pl controvflag</th>
      <th>Pl pnum</th>
      <th>Pl orbper</th>
      <th>Pl orbsmax</th>
      <th>Pl orbeccen</th>
      <th>Pl orbincl</th>
      <th>Pl bmassj</th>
      <th>Pl radj</th>
      <th>Pl dens</th>
      <th>Pl nnotes</th>
      <th>St dist</th>
      <th>Gaia dist</th>
      <th>St optmag</th>
      <th>St optband</th>
      <th>Gaia gmag</th>
      <th>St teff</th>
      <th>St mass</th>
      <th>St rad</th>
      <th>Rowupdate</th>
      <th>Pl eqt</th>
      <th>Pl masse</th>
      <th>Pl ratdor</th>
      <th>Pl ratror</th>
      <th>Pl status</th>
      <th>Pl mnum</th>
      <th>Pl publ date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.loc_rowid %></td>
        <td><%= planet.pl_hostname %></td>
        <td><%= planet.pl_letter %></td>
        <td><%= planet.pl_name %></td>
        <td><%= planet.pl_controvflag %></td>
        <td><%= planet.pl_pnum %></td>
        <td><%= planet.pl_orbper %></td>
        <td><%= planet.pl_orbsmax %></td>
        <td><%= planet.pl_orbeccen %></td>
        <td><%= planet.pl_orbincl %></td>
        <td><%= planet.pl_bmassj %></td>
        <td><%= planet.pl_radj %></td>
        <td><%= planet.pl_dens %></td>
        <td><%= planet.pl_nnotes %></td>
        <td><%= planet.st_dist %></td>
        <td><%= planet.gaia_dist %></td>
        <td><%= planet.st_optmag %></td>
        <td><%= planet.st_optband %></td>
        <td><%= planet.gaia_gmag %></td>
        <td><%= planet.st_teff %></td>
        <td><%= planet.st_mass %></td>
        <td><%= planet.st_rad %></td>
        <td><%= planet.rowupdate %></td>
        <td><%= planet.pl_eqt %></td>
        <td><%= planet.pl_masse %></td>
        <td><%= planet.pl_ratdor %></td>
        <td><%= planet.pl_ratror %></td>
        <td><%= planet.pl_status %></td>
        <td><%= planet.pl_mnum %></td>
        <td><%= planet.pl_publ_date %></td>
        <td><%= link_to 'Show', planet %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loc rowid:</strong>
  <%= @planet.loc_rowid %>
</p>

<p>
  <strong>Pl hostname:</strong>
  <%= @planet.pl_hostname %>
</p>

<p>
  <strong>Pl letter:</strong>
  <%= @planet.pl_letter %>
</p>

<p>
  <strong>Pl name:</strong>
  <%= @planet.pl_name %>
</p>

<p>
  <strong>Pl controvflag:</strong>
  <%= @planet.pl_controvflag %>
</p>

<p>
  <strong>Pl pnum:</strong>
  <%= @planet.pl_pnum %>
</p>

<p>
  <strong>Pl orbper:</strong>
  <%= @planet.pl_orbper %>
</p>

<p>
  <strong>Pl orbsmax:</strong>
  <%= @planet.pl_orbsmax %>
</p>

<p>
  <strong>Pl orbeccen:</strong>
  <%= @planet.pl_orbeccen %>
</p>

<p>
  <strong>Pl orbincl:</strong>
  <%= @planet.pl_orbincl %>
</p>

<p>
  <strong>Pl bmassj:</strong>
  <%= @planet.pl_bmassj %>
</p>

<p>
  <strong>Pl radj:</strong>
  <%= @planet.pl_radj %>
</p>

<p>
  <strong>Pl dens:</strong>
  <%= @planet.pl_dens %>
</p>

<p>
  <strong>Pl nnotes:</strong>
  <%= @planet.pl_nnotes %>
</p>

<p>
  <strong>St dist:</strong>
  <%= @planet.st_dist %>
</p>

<p>
  <strong>Gaia dist:</strong>
  <%= @planet.gaia_dist %>
</p>

<p>
  <strong>St optmag:</strong>
  <%= @planet.st_optmag %>
</p>

<p>
  <strong>St optband:</strong>
  <%= @planet.st_optband %>
</p>

<p>
  <strong>Gaia gmag:</strong>
  <%= @planet.gaia_gmag %>
</p>

<p>
  <strong>St teff:</strong>
  <%= @planet.st_teff %>
</p>

<p>
  <strong>St mass:</strong>
  <%= @planet.st_mass %>
</p>

<p>
  <strong>St rad:</strong>
  <%= @planet.st_rad %>
</p>

<p>
  <strong>Rowupdate:</strong>
  <%= @planet.rowupdate %>
</p>

<p>
  <strong>Pl eqt:</strong>
  <%= @planet.pl_eqt %>
</p>

<p>
  <strong>Pl masse:</strong>
  <%= @planet.pl_masse %>
</p>

<p>
  <strong>Pl ratdor:</strong>
  <%= @planet.pl_ratdor %>
</p>

<p>
  <strong>Pl ratror:</strong>
  <%= @planet.pl_ratror %>
</p>

<p>
  <strong>Pl status:</strong>
  <%= @planet.pl_status %>
</p>

<p>
  <strong>Pl mnum:</strong>
  <%= @planet.pl_mnum %>
</p>

<p>
  <strong>Pl publ date:</strong>
  <%= @planet.pl_publ_date %>
</p>

<%= link_to 'Back', planets_path %>